### ISSUE TITLE
Padding on the right

### ISSUE THREAD

**Issue by antonio-petricca** [basilebong/bootstrap4-fullscreen-modal#2]
Hi, as you can see by the attached image:

![image](https://user-images.githubusercontent.com/6660386/65744617-2f816b00-e0f9-11e9-9ab0-016cb2f39be8.png)

it introduces a right padding (I don't know why), but I would suggest you a workaround:

```css
.modal.modal-fullscreen .modal-dialog {
  width: 101%; /* Remove right padding by 101% */
  height: 100%;
  margin: 0;
  padding: 0;
  max-width: none; 
}
```

![image](https://user-images.githubusercontent.com/6660386/65744765-a0288780-e0f9-11e9-8372-a149a3669a10.png)

Thank you so much.
